name: Khan
on: 
    push:
        branches:
            - main
jobs:
    latest:
        runs-on: Ubuntu-latest
       steps :
            -name: Good Morning
            run: echo "Hneef Ha."
            
